"""Add is_visible to GalleryMedia

Revision ID: 002de3f98f9f
Revises: cfac14d7f0f0
Create Date: 2026-08-01 15:52:09.885976

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '002de3f98f9f'
down_revision: Union[str, Sequence[str], None] = 'cfac14d7f0f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gallery_media_created_at'), table_name='gallery_media')
    op.drop_index(op.f('ix_gallery_media_order'), table_name='gallery_media')
    op.drop_table('gallery_media')
    op.drop_table('tts_cache')
    op.drop_index(op.f('ix_museum_chat_messages_id'), table_name='museum_chat_messages')
    op.drop_index(op.f('ix_museum_chat_room_time'), table_name='museum_chat_messages')
    op.drop_table('museum_chat_messages')
    op.drop_index(op.f('ix_gallery_categories_slug'), table_name='gallery_categories')
    op.drop_table('gallery_categories')
    op.create_index(op.f('ix_experiences_company'), 'experiences', ['company'], unique=False)
    op.create_index(op.f('ix_experiences_order'), 'experiences', ['order'], unique=False)
    op.create_index(op.f('ix_writings_order'), 'writings', ['order'], unique=False)
    op.create_index(op.f('ix_writings_published_at'), 'writings', ['published_at'], unique=False)
    op.create_index(op.f('ix_writings_title'), 'writings', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_writings_title'), table_name='writings')
    op.drop_index(op.f('ix_writings_published_at'), table_name='writings')
    op.drop_index(op.f('ix_writings_order'), table_name='writings')
    op.drop_index(op.f('ix_experiences_order'), table_name='experiences')
    op.drop_index(op.f('ix_experiences_company'), table_name='experiences')
    op.create_table('gallery_categories',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('slug', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('label', mysql.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gallery_categories_slug'), 'gallery_categories', ['slug'], unique=True)
    op.create_table('museum_chat_messages',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('room_id', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('sender_id', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('sender_name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('sender_color', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('is_admin', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('message', mysql.TEXT(), nullable=False),
    sa.Column('timestamp', mysql.FLOAT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_museum_chat_room_time'), 'museum_chat_messages', ['room_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_museum_chat_messages_id'), 'museum_chat_messages', ['id'], unique=False)
    op.create_table('tts_cache',
    sa.Column('text_hash', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('text_content', mysql.TEXT(), nullable=False),
    sa.Column('audio_base64', mysql.TEXT(), nullable=False),
    sa.Column('audio_format', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('text_hash')
    )
    op.create_table('gallery_media',
    sa.Column('id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('url', mysql.VARCHAR(length=500), nullable=False),
    sa.Column('media_type', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('caption', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('order', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('category', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('title', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.Column('location', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('date_taken', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('camera', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('lens', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('tags', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('is_featured', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gallery_media_order'), 'gallery_media', ['order'], unique=False)
    op.create_index(op.f('ix_gallery_media_created_at'), 'gallery_media', ['created_at'], unique=False)
    # ### end Alembic commands ###
