"""Expand TerminalLog with ip, device, response

Revision ID: 65b63dda4338
Revises: 57099d2401d3
Create Date: 2026-07-07 23:33:52.441745

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65b63dda4338'
down_revision: Union[str, Sequence[str], None] = '57099d2401d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('terminal_logs', sa.Column('response_text', sa.Text(), nullable=True))
    op.add_column('terminal_logs', sa.Column('ip_address', sa.String(length=255), nullable=True))
    op.add_column('terminal_logs', sa.Column('user_agent', sa.Text(), nullable=True))
    op.add_column('terminal_logs', sa.Column('execution_time_ms', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('terminal_logs', 'execution_time_ms')
    op.drop_column('terminal_logs', 'user_agent')
    op.drop_column('terminal_logs', 'ip_address')
    op.drop_column('terminal_logs', 'response_text')
    # ### end Alembic commands ###
