"""Add geo and browser analytics columns

Revision ID: cfac14d7f0f0
Revises: 65b63dda4338
Create Date: 2026-07-07 23:46:31.957393

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cfac14d7f0f0'
down_revision: Union[str, Sequence[str], None] = '65b63dda4338'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('terminal_logs', sa.Column('country', sa.String(length=100), nullable=True))
    op.add_column('terminal_logs', sa.Column('city', sa.String(length=100), nullable=True))
    op.add_column('terminal_logs', sa.Column('screen_width', sa.Integer(), nullable=True))
    op.add_column('terminal_logs', sa.Column('screen_height', sa.Integer(), nullable=True))
    op.add_column('terminal_logs', sa.Column('language', sa.String(length=50), nullable=True))
    op.add_column('terminal_logs', sa.Column('referrer', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('terminal_logs', 'referrer')
    op.drop_column('terminal_logs', 'language')
    op.drop_column('terminal_logs', 'screen_height')
    op.drop_column('terminal_logs', 'screen_width')
    op.drop_column('terminal_logs', 'city')
    op.drop_column('terminal_logs', 'country')
    # ### end Alembic commands ###
